#server:
#  port: 8082

spring.datasource.url: jdbc:h2:file:./camunda-h2-database


camunda:
  bpm:
    admin-user:
      id: root
      password: root
    filter.create: All Tasks
    run:
      cors:
        enabled: true
        allowed-origins: "*"
#    process-engine-name: "TestEngine"
#    job-execution:
#      core-pool-size: 50
#      max-pool-size: 50
#      queue-capacity: 10

